TRAIN:
  pretained_renderer: ''
  seed: 10
  partial_load: False
  N_iters: 100000
  precrop_iters: 500
  LR:
    lr: 5.0e-4
    use_scheduler: True
    decay_epochs: 10000
  imgW: 400
  imgH: 400
  scale: 1.0
  save_interval: 500
  log_interval: 10

TEST:
  camera_angle_x: 0.323
  imgW: 400
  imgH: 400
  scale: 1.0
  data_path: '/data/syguan/fluid_simulation/release/data_release/watercube/honeycone/view_1/train/particles'
  start_index: 0
  end_index: 50
  near: 9.0
  far: 13.0
  
# configs of renderer
RENDERER:
  use_mask: True
  ray:
    ray_chunk: 1024
    N_importance: 128  # num of fine sample point
    N_samples: 64    # num of coarse sample point
  NN_search:
    fix_radius: True
    particle_radius: 0.025
    search_raduis_scale: 9.0
    N_neighbor: 20
  encoding:
    density: True
    var: True
    smoothed_pos: True
    smoothed_dir: True
    exclude_ray: True
    same_smooth_factor: False